site_name: GIS Career Entry Guide
nav:
  - Index: 
    - GIS入行指南: index.md
  - 前言: 
    - 前言: GIS入行指南/前言.md
  - 内容规划: 
    - 内容规划: GIS入行指南/内容规划.md
  - 书籍和课程推荐:
    - 书籍和课程推荐: GIS入行指南/书籍和课程推荐.md
    - 阅读推荐:
      - 浏览器工作原理: GIS入行指南/书籍和课程推荐/浏览器工作原理.md
      - 奇幻地图设计指南: GIS入行指南/书籍和课程推荐/简化的奇幻地图设计指南（详细版）.md
  - 工具:
    - 工具: GIS入行指南/工具.md
    - 关于电脑: GIS入行指南/关于电脑.md
    - 信息检索: GIS入行指南/信息检索.md
    - 科学上网: GIS入行指南/科学上网.md
    - 命令行: GIS入行指南/命令行.md
    - IDE: GIS入行指南/IDE.md
    - 版本控制工具: GIS入行指南/版本控制工具.md
    - 正则表达式: GIS入行指南/正则表达式.md
    - Docker: GIS入行指南/Docker.md
    - 笔记工具: GIS入行指南/笔记工具.md
    - 推荐软件: GIS入行指南/推荐软件.md
  - 数据:
    - 数据: GIS入行指南/数据.md
    - 文本文件和二进制文件: GIS入行指南/文本文件和二进制文件.md
    - 数据交换格式: GIS入行指南/数据交换格式.md
    - 矢量数据模型: GIS入行指南/矢量数据模型.md
    - 栅格数据模型: GIS入行指南/栅格数据模型.md
    - 三维数据模型: GIS入行指南/三维数据模型.md
    - 地图服务: GIS入行指南/地图服务.md
    - 数据获取: GIS入行指南/数据获取.md
    - 关于保密: GIS入行指南/关于保密.md
  - 结语:
    - 结语: GIS入行指南/结语.md
theme:
  name: readthedocs
extra_css:
  - style.css